#!/usr/bin/env bash
# -------------------------------------------------------------
#  pack-config.sh
#  Packs .zshrc, .zsh/ and .config/ into config.tgz.
#
#  The archive is committed to this repository, so it is built
#  reproducibly: identical input produces a byte-identical file.
#  Without the flags below, tar and gzip record the current time and
#  the building user, so every run would create a new blob and show
#  up in "git status" even when nothing was edited.
#
#  Unpack on the target machine with:
#      tar -xzf config.tgz -C ~
#
#  Note that tmux reads EVERY config it finds and merges them, so an
#  older ~/.tmux.conf keeps applying next to ~/.config/tmux/tmux.conf.
#  Remove it after unpacking:
#      rm -f ~/.tmux.conf
# -------------------------------------------------------------

set -euo pipefail

cd "$(dirname "$0")"

ARCHIVE="config.tgz"
SOURCES=(.zshrc .zsh .config)

# GNU tar only -- bsdtar (macOS) has no --sort, and without it the
# archive would not be reproducible. Fail loudly instead of writing
# something that churns on every commit.
if ! tar --version 2>/dev/null | head -1 | grep -q "GNU tar"; then
    echo "pack-config: needs GNU tar (macOS: brew install gnu-tar, then use gtar)" >&2
    exit 1
fi

for src in "${SOURCES[@]}"; do
    if [ ! -e "$src" ]; then
        echo "pack-config: missing $src -- run this from the repository root" >&2
        exit 1
    fi
done

# The archive is committed, so it must not carry machine-local files.
# tar does not read .gitignore, so the ignored paths are repeated here --
# keep this list in sync with .gitignore.
EXCLUDES=(
    --exclude=".zsh/local/*.zsh"   # machine-local, may hold tokens
    --exclude=".config/envman"     # generated by envman
    --exclude=".zsh_cache"         # generated completions
    --exclude-vcs                  # .git and friends
)

# --sort=name        stable entry order, independent of readdir()
# --mtime            one fixed timestamp instead of the real ones
# --owner/--group    no local uid/gid baked in
# gzip -n            no timestamp and no filename in the gzip header
tar --sort=name \
    --mtime="UTC 2020-01-01" \
    --owner=0 --group=0 --numeric-owner \
    "${EXCLUDES[@]}" \
    -cf - "${SOURCES[@]}" \
  | gzip -n -9 > "$ARCHIVE"

# Read the listing once. Note the herestrings below instead of pipes:
# "grep -q" exits on the first match, which kills tar with SIGPIPE, and
# under "set -o pipefail" that turns a successful check into a failure --
# but only when tar has not already finished writing into the pipe buffer,
# so it fails intermittently. A herestring has no pipeline at all.
names=$(tar -tzf "$ARCHIVE")
detail=$(tar -tvzf "$ARCHIVE")

entries=$(wc -l <<< "$names" | tr -d ' ')
size=$(du -h "$ARCHIVE" | cut -f1)

echo "$ARCHIVE  --  $entries entries, $size"

# keyhelp.sh is useless without its executable bit; verify it survived
if grep -q '^-rwx.*\.config/tmux/keyhelp\.sh$' <<< "$detail"; then
    echo "  keyhelp.sh: executable bit kept"
else
    echo "  WARNING: keyhelp.sh lost its executable bit" >&2
fi

# Safety net: the archive goes into the repository, so nothing git would
# ignore may be inside it. Checked rather than assumed -- an exclude typo
# would otherwise leak a local file with tokens into a commit.
if command -v git >/dev/null 2>&1 && git rev-parse --git-dir >/dev/null 2>&1; then
    leaked=$(git check-ignore --stdin <<< "$(sed 's#/$##' <<< "$names")" 2>/dev/null || true)
    if [ -n "$leaked" ]; then
        echo "  ERROR: archive contains files git ignores:" >&2
        printf '    %s\n' $leaked >&2
        rm -f "$ARCHIVE"
        exit 1
    fi
    echo "  no git-ignored files inside"
fi
